$schema: https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#
contentVersion: 1.0.0.0
parameters:
  rgName:
    value: swoo-rg-uks
  rgLocation:
    value: uksouth
  tags:
    value: {}
